name: CI-CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "No tests added yet"

      - name: Build Docker Image
        run: |
          docker build -t drone_detection_image .

      - name: Push Docker Image to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag & Push Image
        run: |
          docker tag drone_detection_image ghcr.io/${{ github.repository }}/drone_detection_image:latest
          docker push ghcr.io/${{ github.repository }}/drone_detection_image:latest
